#!/usr/bin/env python3

import uproot, os
from tqdm import tqdm
import datetime

filename_file = "filenames.txt"
error_log_path = "error_log.txt"

# ------------------------------------------------
# Modify directory to your root file and variables to check to suit your needs
# ------------------------------------------------
ROOTfile_directory = "/work/hallc/c-rsidis/skimfiles/pass0"

variables_to_check = [
    "H_gtr_dp", "P_gtr_dp",
    "H_cal_etottracknorm", "P_cal_etottracknorm",
    "P_ngcer_npeSum", "P_hgcer_npeSum", "H_cer_npeSum"
]

# ------------------------------------------------
# Defining function to open root files
# ------------------------------------------------
def read_filenames(filepath):
    with open(filepath, "r") as f:
        data = f.read().strip()
        return [x.strip() for x in data.split(",") if x.strip()]

# ------------------------------------------------
# Defining function to distinguish between files and establish mapping of variables
# You may need to alter this to suit your needs
# ------------------------------------------------
def main():
    errors_by_file = {}
    filenames = read_filenames(filename_file)

    for filename in tqdm(filenames, desc="Checking files", unit="file"):
        file_path = os.path.join(ROOTfile_directory, filename)
        file_errors = []

        if "coin" in filename and "shms" not in filename and "hms" not in filename:
            vars_to_check = variables_to_check
        elif "hms" in filename and "shms" not in filename:
            vars_to_check = [v for v in variables_to_check if v.startswith("H")]
        elif "shms" in filename:
            vars_to_check = [v for v in variables_to_check if v.startswith("P")]
        else:
            file_errors.append("Filename does not match any recognized pattern.")
            errors_by_file[filename] = file_errors
            continue

        try:
            with uproot.open(file_path) as file:
                if "T" not in file:
                    file_errors.append("Missing tree 'T'.")
                else:
                    tree = file["T"]
                    missing_vars = [v for v in vars_to_check if v not in tree.keys()]
                    if missing_vars:
                        file_errors.append("Missing variables: " + ", ".join(missing_vars))
        except Exception as e:
            file_errors.append(f"File load error: {e}")

        if file_errors:
            errors_by_file[filename] = file_errors

# ------------------------------------------------
# Writing the error report
# ------------------------------------------------
    with open(error_log_path, "w") as f:
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        f.write(f"Error Report - Generated by TESTING_ROOTfiles.py\n")
        f.write(f"Developed by R. Elder, November 2025\n")
        f.write(f"{timestamp}\n\n")
        if not errors_by_file:
            f.write("No errors found!\n")
        else:
            for filename, errs in errors_by_file.items():
                f.write("!============================================\n")
                f.write(f"{filename}\n")
                f.write("!============================================\n")
                for err in errs:
                    f.write(f"{err}\n")
                f.write("\n")

    print(f"Check complete. Errors written to {error_log_path}")

if __name__ == "__main__":
    main()
